export const ProjectCardObjCurrent = {
  id: "petretreat",
  title:
    "Customisable fullstack application for Boarding Kennels and Pet Retreats",
  subTitle: "This is still a work in progress",
  img: require("../../assets/PetRetreat/Landing-Page.png").default,
  alt: "Landing page for a fictitious Pet retreat company",
  tags: ["NextJS", "tRPC", "MySQL", "Figma", "Prisma", "PlanetScale"],
  GitRepo: "https://github.com/MrAjMann/BoardingKennel",
  ProjectPage: "projects/petretreat",
  imgStartIsTrue: "",
  imgStart: "",
  start: "",
};
export const ProjectCardObjOne = {
  id: "devsearch",
  title: "DevSearch.io",
  subTitle: "Developer Job Search Engine",
  img: require("../../assets/DevSearch/DevSearchLandingPage.png").default,
  alt: "Preview of DevSearch.io",
  tags: ["React", "Axios", "MongoDb", "Figma", "Styled Components"],
  GitRepo: "https://github.com/devsearch-team/devsearch",
  ProjectPage: "projects/devsearch",
  imgStartIsTrue: "",
  imgStart: "true",
  start: "true",
};
export const ProjectCardObjTwo = {
  id: "comparitube",
  title: "CompariTube",
  subTitle: "YouTube channel comparison app",
  img: require("../../assets/CompariTube.png").default,
  alt: "Preview of compariTube",
  tags: ["JavaScript", "HTML", "SASS", "Figma"],
  GitRepo: "https://github.com/RAMTeam/CompariTube.git",
  ProjectPage: "projects/comparitube",
  imgStartIsTrue: "",
  imgStart: "",
  start: "",
};

export const ProjectCardObjThree = {
  title: "Third Dimension",
  subTitle: "Ecommerce Application with user Authentication",
  img: require("../../assets/ThirdDimension/ThirdDimensionLP.png").default,
  alt: "Landing Page of Lotus Loft",
  tags: ["RubyonRails", "PostgreSQL"],
  GitRepo: "https://github.com/RAMTeam/compariTube.git",
  ProjectPage: "projects/thirddimension",
  imgStartIsTrue: "",
  imgStart: "",
  start: "",
};
export const ProjectCardObjFour = {
  title: "Arcade Secretary",
  subTitle: "Arcade Secretary is a score-based speed typing game",
  img: require("../../assets/ArcadeSecretary/LandingPage.png").default,
  alt: "Landing Page of Arcade Secretary",
  tags: ["ReactJs", "Faker"],
  GitRepo: "https://github.com/Hack-Overflow-Team/Arcade-Secretary",
  ProjectPage: "projects/arcadesecretary",
  imgStartIsTrue: "",
  imgStart: "true",
  start: "true",
};
